// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnnwAJ2nTFrbe4mDG8jL8a_FlhxmZFqRw',
    appId: '1:761082290929:web:e3a50fb8860e8c961c3f50',
    messagingSenderId: '761082290929',
    projectId: 'flutter-test1-db810',
    authDomain: 'flutter-test1-db810.firebaseapp.com',
    storageBucket: 'flutter-test1-db810.firebasestorage.app',
    measurementId: 'G-GD0K5LB9QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4jHUMEANW0Wojrwpg1SeEMQzlifhqgYo',
    appId: '1:761082290929:android:36be7db9c0d7fb8f1c3f50',
    messagingSenderId: '761082290929',
    projectId: 'flutter-test1-db810',
    storageBucket: 'flutter-test1-db810.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtJPlLMJLI2h5PcIQG0BdWiZ64sV4-ay8',
    appId: '1:761082290929:ios:b8abdcc077d9b3a01c3f50',
    messagingSenderId: '761082290929',
    projectId: 'flutter-test1-db810',
    storageBucket: 'flutter-test1-db810.firebasestorage.app',
    iosBundleId: 'com.example.flutterTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtJPlLMJLI2h5PcIQG0BdWiZ64sV4-ay8',
    appId: '1:761082290929:ios:b8abdcc077d9b3a01c3f50',
    messagingSenderId: '761082290929',
    projectId: 'flutter-test1-db810',
    storageBucket: 'flutter-test1-db810.firebasestorage.app',
    iosBundleId: 'com.example.flutterTest1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnnwAJ2nTFrbe4mDG8jL8a_FlhxmZFqRw',
    appId: '1:761082290929:web:7cc98acc78e4eed41c3f50',
    messagingSenderId: '761082290929',
    projectId: 'flutter-test1-db810',
    authDomain: 'flutter-test1-db810.firebaseapp.com',
    storageBucket: 'flutter-test1-db810.firebasestorage.app',
    measurementId: 'G-PL3J1JN1M9',
  );
}
